package org.edano.assignment.scratchgame.model;

public enum ComboGroup {
    SAME_SYMBOLS, HORIZONTALLY_LINEAR_SYMBOLS, VERTICALLY_LINEAR_SYMBOLS,
    LTR_DIAGONALLY_LINEAR_SYMBOLS, RTL_DIAGONALLY_LINEAR_SYMBOLS;
}
